prefs={
  width=1024,
  height=768,
  maximizedWindow=false,
  fullscreen=false,
  noImages = false,
  creatureShadows = true,
  creatureAnimations = true,
  asciiSize = 14,
  fontSize = 14,
  descFontSize = 12,
  soundVolume = 100,
  musicVolume = 100,
  spellShortcuts = true,
  mouseMovesMap = true,
  arrowKeys = true,
  autosaveTurns=false,
  noSmoothMovement=false,
  noSmoothCamera=false,
  statsOnSidebar=true,
  plainFonts=false,
  minimap=true,
  lastMods={},
  vsync=true,
  uiScale=1,
}

require "keybindings"